### PR TITLE
Systemd hardening

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by eauchat** [comment]
Heyyo @ericgaspar, thanks for your continuous contributions to improve this package :)
I feel a bit like a chicken in front of a knife trying to review your proposal of change. I don't understand them much, but I'm ok with the change since the idea is to stick close to example_ynh.
I'm don't have a working yunohost developing environment to test if those changes may break the app at the moment. If some other contributor has the possibility to do it, that"s great.

**Comment by ericgaspar** [comment]
Yep, sorry I havn't given much context...
Basically I am trying to harden systemd security policy on all the apps that use systemd services...
As for the restore script, those two lines are no longer needed: cf this PR -> https://github.com/YunoHost/example_ynh/pull/171

**Comment by eauchat** [comment]
If you want to merge that's fine for me. If you feel like it's good to have some reviews, or there is a risk that the app doesn't work and should be tested beforehand, maybe it's good to find some contributor that could do it. Otherwise feel free to do as you think is good.

**Comment by alexAubin** [comment]
Merging to testing

**Pull request merged**
